apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami/mariadb
  namespace: mariadb
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
values:
  image:
    registry: docker.io
    repository: bitnami/mariadb
    tag: 11.3.2-debian-12-r1
    pullPolicy: IfNotPresent
    pullSecrets: []
    debug: false
