---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: gloo-demo-system
  path: ./apps/mariadb
  prune: true
  wait: true
  timeout: 5m0s