---
apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: istio-ingressgateway-cluster2
  namespace: gloo-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  installations:
      # The revision for this installation, such as $ISTIO_TAG_REVISION
    - gatewayRevision: $ISTIO_TAG_REVISION
      # List all workload clusters to install Istio into
      clusters:
      - name: cluster2
        # If set to true, the spec for this revision is applied in the cluster
        activeGateway: false
      istioOperatorSpec:
        # No control plane components are installed
        profile: empty
        # Solo.io Istio distribution repository; required for Gloo Istio.
        # You get the repo key from your Solo Account Representative.
        hub: us-docker.pkg.dev/gloo-mesh/$ISTIO_HUB
        # The Solo.io Gloo Istio tag
        tag: $ISTIO_TARGET_REVISION-solo
        values:
          gateways:
            istio-ingressgateway:
              customService: true
        components:
          ingressGateways:
            - name: istio-ingressgateway
              namespace: istio-gateways
              enabled: true
              label:
                istio: ingressgateway