apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: mariadb
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mariadb
  namespace: mariadb
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: mariadb
        version: 18.0.2
      interval: 5m
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: ${MARIADB_IMAGE_VERSION}
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false  
    