apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mariadb
  namespace: mariadb
spec:
  interval: 5m
  url: https://charts.bitnami.com/bitnami
  values:
    image:
      registry: docker.io
      repository: bitnami/mariadb
      tag: ${MARIADB_IMAGE_VERSION}
      pullPolicy: IfNotPresent
      pullSecrets: []
      debug: false